--- 
- name: Write hostname to file
  hosts: all
  vars: 
    version4asc: '0.0.0.1'
    # host: "{{ ansible_facts['hostname'] }}"
    host: "otherserver"
 
  tasks:
  - name: Write file from template
    ansible.builtin.template:
      src: inputfile.j2
      dest: outputfile.conf

