---
- name: Configure NFTables Router
  hosts: router
  become: yes
  tasks:
    - name: Install nftables
      apt:
        name: nftables
        state: present

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes

    - name: Configure NFTables rules
      copy:
        dest: /etc/nftables.conf
        content: |
          table ip nat {
              chain postrouting {
                  type nat hook postrouting priority 100; policy accept;
                  oifname "eth0" masquerade
              }
          }
    - name: Enable and start nftables service
      systemd:
        name: nftables
        enabled: yes
        state: started
