---
- name: Run embedded script using Ansible asc
  hosts: all
  become: yes 

  tasks:
    - name: Execute embedded script
      shell: |
        set -x
        echo "This is a script running from within the playbook"
        cat <<EOF > /etc/network/interfaces.d/eth1
        auto eth1         
        iface eth1 inet static
        address 192.168.66.252/24
        EOF
        echo "# Fertig ansible asc" >> /etc/network/interfaces.d/eth1
        # Add your script commands here
        echo "Script execution completed"
