---
- name: Configure network for static IP address
  hosts: all
  become: yes
 
  tasks:
    - name: Configure network interface
      community.network.ipadm_addr:
        dest: /etc/network/interfaces.d/eth1
        iface: eth1
        option: mtu
        value: 8000
          #        backup: true
          #        state: present
          #      register: eth1_cfg      
 

