---
- name: Manage sudoers.d files
  hosts: all
  become: true
  vars:
    user: deploy
  tasks:
    - name: Add user to sudoers.d
      lineinfile:
        path: /etc/sudoers.d/{{ user }}
        line: '{{ user }} ALL=(ALL) NOPASSWD: ALL'
        state: present
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
