#!/usr/bin/ansible-playbook --connection=local --inventory=localhost, 
# Please use it only as root.
---
- name: Manage sudoers.d files
  hosts: localhost
  become: true
  tasks:
    - name: Add user to sudoers.d
      lineinfile:
        path: /etc/sudoers.d/sudo4ansible
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        state: present
        create: yes
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
