#!/usr/bin/ansible-playbook --connection=local --inventory=localhost, -e 'my_hosts=localhost' $@ 
---
- name: Update debian system
  hosts: hosts: '{{ my_hosts | default("all") }}'
  become: true
  tasks:  
    - name: Update apt package lists
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: true
        autoclean: true
